name: ImgMap
version: 1-rw
main: ga.nurupeaches.imgmap.ImgMapPlugin

commands:
    drawimage:
        permission: imgmap.command.drawimage
    drawvideo:
        permission: imgmap.command.drawvideo
    joinvideo:
        permission: imgmap.command.joinvideo
    lolgameboy:
        permission: imgmap.command.lolgameboy